services:
  - type: web
    name: pokgamebattle-backend
    runtime: node
    repo: https://github.com/Al-Amer/PokGameBattle
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
